### ISSUE TITLE
Data channels

### ISSUE THREAD

**Issue by lbdroid** [NethServer/janus-gateway#32]
A high significance use for this project is now for nextcloud talk/spreed high performance backend (signaling), which depends on Data Channels.

This requires only the addition of usrsctp, which is supported by Fedora 31+ as can be found here;
https://koji.fedoraproject.org/koji/packageinfo?packageID=32595

The src.rpm's can be used to generate usrsctp for EL7/8.

I recommend adding usrsctp-devel as a build dependency and usrsctp as an installation dependency. This would take away some of the pain in getting the signaling server running.

Or in the minimum, at least add it to the README that Data Channels can be enabled simply by installing usrsctp-devel when building and usrsctp when running.

**Comment by gsanchietti** [comment]
Please take a look to #31 

The work can be done, but I don't know if it's worth the effort.
Also note that janus-gateway releases within NethServer is always a little older than upstream one.

@alepolidori @Stell0 what do you think?

**Comment by Stell0** [comment]
It seems easy, I also don't know if it' is worth it. It is needed by NextCloud talk, right? If it is, I think that it would be nice to add this feature to our build in order to make it useful to more people.

**Comment by lbdroid** [comment]
Yes, Nextcloud Talk's high performance backend (MCU, which is required in order to host a conference with more than 2-3 participants) *requires* this to be enabled.

Its not written in the requirements/readme, but reference to this requirement can be found in bug reports;
https://github.com/strukturag/nextcloud-spreed-signaling/issues/9

**Comment by alepolidori** [comment]
Hi @lbdroid , thank you for your issue.
As you already said, `usrsctp` is needed in order to have data channels support, but unfortunately it is not provided by CentOS repositories (AFAIK). Today we don't have resources to spent on developing and maintaining the rpm, but we would be very happy if you would like to contribute with a PR.

**Comment by alepolidori** [comment]
I close the issue. Feel free to open a new issue for DataChannel support on [NethServer main track](https://github.com/nethserver/dev/issues) if you would like to participate developing `usrsctp` package.
